### ISSUE TITLE
 Failed to execute goal on project talen

### ISSUE THREAD

**Issue by Roshanson** [mayhewsw/ner-annotation#19]
Hi ,Is it supported on win10

when i  run  ./scripts/run.sh
I see:

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building talen 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.0.2.RELEASE:run (default-cli) > test-compi                                                                                                                                                                                               le @ talen >>>
[WARNING] The POM for edu.illinois.cs.cogcomp:illinois-core-utilities:jar:4.0.4                                                                                                                                                                                                is missing, no dependency information available
[WARNING] The POM for edu.illinois.cs.cogcomp:illinois-corpusreaders:jar:3.1.19                                                                                                                                                                                                is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.742 s
[INFO] Finished at: 2018-07-23T11:32:01+08:00
[INFO] Final Memory: 18M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project talen: Could not resolve dependencies                                                                                                                                                                                                for project edu.illinois.cs.cogcomp:talen:jar:0.1.0: The following artifacts cou                                                                                                                                                                                               ld not be resolved: edu.illinois.cs.cogcomp:illinois-core-utilities:jar:4.0.4, e                                                                                                                                                                                               du.illinois.cs.cogcomp:illinois-corpusreaders:jar:3.1.19: Failure to find edu.il                                                                                                                                                                                               linois.cs.cogcomp:illinois-core-utilities:jar:4.0.4 in http://maven.release.ctri                                                                                                                                                                                               pcorp.com/nexus/content/groups/public was cached in the local repository, resolu                                                                                                                                                                                               tion will not be reattempted until the update interval of nexus has elapsed or u                                                                                                                                                                                               pdates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                                                                                                                                                               ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                                                                                                                                                               d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso                                                                                                                                                                                               lutionException

So i can't download some files under edu.illinois.cs.cogcomp:

**Comment by mayhewsw** [comment]
I haven't tested it on Windows 10, but it is all based on Java which should be cross-platform. 

It looks as though it can't find the POM for illinois-core-utilities. That file is hosted here: http://cogcomp.org/m2repo/edu/illinois/cs/cogcomp/illinois-core-utilities/4.0.4/ Can you access this link?

**Comment by Roshanson** [comment]
yes  i can access this link.  
Thanks = =

**Comment by eaubin** [comment]
I fixed a similar problem by ensuring the local artifact mirror configured in .m2/settings file did not mirror the cogcomp repo.

**Comment by mayhewsw** [comment]
Thanks @eaubin.

@Roshanson is this issue resolved for you?

**Comment by mfirry** [comment]
I'm facing the same issue. How do I solve this?

Looks like `http://cogcomp.org/m2repo/` isn't working for getting required deps
