### ISSUE TITLE
Instructions on loading data

### ISSUE THREAD

**Issue by janenie** [mayhewsw/ner-annotation#27]
Hi, I am very new to this NER annotation tool. 
I found there was no instructions on how to change data (i.e., specify each column in the conll.txt). And I also change the NER labels, in data/config. I found it cannot be tagged ever since. 

Could you give some of more details on how to use this toolkit with user-specific data and labels?

**Comment by mayhewsw** [comment]
Hi! Thanks for using TALEN. I'm not sure I understand the problem. What do you want to change about the columns? [This file](https://github.com/CogComp/talen/blob/master/src/main/java/io/github/mayhewsw/utils/ColumnReader.java#L139) dictates how the column files are read. Perhaps you want to change that?

Aternately, if you just want to convert text into the TExtAnnotation JSON formet, you can use [this script](https://github.com/CogComp/talen/blob/master/data/txt2tajson.py).

**Comment by mayhewsw** [comment]
I'm not sure if this is the case for you, but there may also be a problem if you have the “-“ character in your document names or document ids.

**Comment by janenie** [comment]
I have fixed the problem, thanks a lot
